run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
